apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-todo-db
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
#  storageClassName: local-storage
  local:
    path: /mnt/tododbdsk
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lfsworkernode02

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-todo-db
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
