apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-app
  name: todo-app
  namespace: sandbox
spec:
  ports:
  - nodePort: 30100
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: todo-app
  type: NodePort
